name: kismetly
description: Kismetly - TR kozmik ana ekran
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.5.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  characters: ^1.4.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.1
  shared_preferences: ^2.2.3
  firebase_core: 4.2.1
  firebase_auth: 6.1.2
  cloud_firestore: 6.1.0
  purchases_flutter: ^8.1.2
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  google_generative_ai: ^0.4.4
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  uuid: ^4.3.3
  phone_numbers_parser: ^9.0.16
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/l10n/
    - lib/data/
    - assets/config/.env

  generate: true
